## save random number
#/random/setSavingFlag

#/gps/verbose 2

## Particle type, position, energy...
/gps/particle gamma
/gps/number 1
# Source position now hardcoded
#/gps/pos/centre  0 0 -22 cm

/gps/ene/type Arb   # important: capital A in Arb
/gps/hist/type arb
/gps/hist/file fission_gamma_ENDF.dat
/gps/hist/inter Lin

#/gps/direction 0 0 1
/gps/ang/type iso
/gps/ang/mintheta 160. degree
/gps/ang/maxtheta 180. degree

/process/inactivate Cerenkov

## Number of events to run
/run/beamOn 4000000