# Macro file for the initialization of example B1
# in interactive mode
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
#/run/initialize
#
# Visualization setting
# need to move this after initialization
# and initialization has to come later due to the macro choise of the geometry
#/control/execute vis.mac
