## save random number
#/random/setSavingFlag

## Particle type, position, energy...
/gps/particle gamma
/gps/number 1

## Particle source distribution and definition
/gps/pos/type Plane
/gps/pos/shape Ellipse
/gps/pos/centre 0. 0. 0. mm
/gps/pos/halfx 0.75 mm
/gps/pos/halfy 1.25 mm

/gps/energy 500. keV
#/gps/direction 0 0 1
/gps/ang/type iso
#/gps/ang/mintheta 160. degree
#/gps/ang/maxtheta 180. degree

#/process/inactivate Cerenkov

## Number of events to run
/run/beamOn 1
