## save random number
#/random/setSavingFlag

## Particle type, position, energy...
#/gps/particle gamma
#/gps/number 1
#/gps/energy 500. keV

/gps/particle ion
/gps/energy 0 keV
/gps/ion 63 152 0 0
/grdm/nucleusLimits 152 152 63 63

## Particle source distribution
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/centre  0 0 1 mm
/gps/pos/radius 0.5 mm
/gps/ang/type iso

#/process/inactivate Cerenkov

## Number of events to run
/run/beamOn 200000
